chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.main_chat_room, name='main_chat_room'), #beta chat link
    path('<str:room_name>/', views.room, name='room'), #final chat link
    path('change_chat_name/<str:chat_url>/', views.change_chat_room, name='change_chat_room'),
    path('friend_chat/<int:other_id>/', views.friend_chat, name='friend_chat'),
]

clique_App/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from chat import views
from Notifications import views as views_notif


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authorize_main.urls')),
    path('posts/', include('posts_app.urls')),
    path('notifications/', include('Notifications.urls')),
    path('chat/', include('chat.urls')),
    path('friends/', include('friends.urls')),
    #debug
    #path('debug/delete_chat_model/', views.clear_all_chats, name='clearchat'),
    #path('debug/delete_user_keys/', views.clear_user_keys, name='clearkeys'),
    #path('debug/delete_all_notifications/', views_notif.delete_all_notifications, name='clearnotifications'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts_app/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
      path('home/', views.PostList, name='hometemplate'),
      path('create_post/', views.create_post_view, name='createposts'),
      path('make_bookmark/<int:post_id>/', views.make_bookmark, name='bookmark'),
      path('getbookmarkinfo_allposts/<int:post_id>/<int:page_number>/', views.getbookmarkinfo_allposts, name='getbookmarkinfo_allposts'),
      
      path('all_posts/',views.PostList,name="postlist"),
      path('bookmarked_posts/', views.BookmarkList, name='bookmarklist'),
      path('my_posts/', views.MyPostList, name='mypostlist'),
      path('my_posts/<int:post_id>/<int:page_number>/',views.MyPostList,name='mypostlist'),
      path('my_applied_posts/', views.ApplyList, name='applylist'),
      
      #path('apply', views.apply_view, name='apply'),
      #path('apply_all_post/', views.redir_2_all_post, name='applyall'),
      path('apply_all_post/<int:page_number>/', views.redir_2_all_post, name='applyall'),
      path('apply_bookmarks/<int:page_number>/', views.redir_2_bookmarked, name='applybookmark'),
      path('apply_bookmarks/', views.redir_2_bookmarked, name='applybookmark'),
      path('apply_form/<int:page_number>/', views.apply_page, name='applyform'),
      path('apply_form/', views.apply_page, name='applyform'),
      path('submit_application/<int:post_id>/<int:page_number>/', views.submit_application, name='submitapp'),
      
      path('delete_bookmark/<int:bookmark_id>/<int:page_number>/', views.delete_my_bookmark, name='delete_my_bookmark'),
      #path('delete_my_post/<int:post_id>/', views.delete_my_post, name='delete_my_post'),
      path('delete_my_post/<int:post_id>/<int:page_number>/', views.delete_my_post, name='delete_my_post'),
      
      path('edit_my_post/', views.edit_my_post, name ='edit_post'),
      
      path('applicant_profile/<int:user_id>/', views.applicant_profile, name='applicant_profile'),
      path('applicant_profile/', views.applicant_profile, name='applicant_profile'),
      path('accept_applicant/', views.accept_applicant, name='accept_applicant'),
      path('accept_applicant/<int:page_num>/', views.accept_applicant, name='accept_applicant'),     
      path('submit_filter_all/', views.filter_keyword_all, name='submit_filter_all'),
      path('submit_filter_applied/', views.filter_keyword_applied, name='submit_filter_applied'),
      path('submit_filter_bookmarked/', views.filter_keyword_bookmarked, name='submit_filter_bookmarked'),
      path('submit_filter_mypost/', views.filter_keyword_mypost, name='filter_keyword_mypost'),
      path('contact_leader/', views.contact_leader, name='contact_leader') 
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authorize_main/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.postgres.fields.array import ArrayField

# Create your models here.

class MyAccountManager(BaseUserManager):
  def create_user(self,email,first_name,last_name,university,major,school_year,password=None):
    if not email:
      raise ValueError("Users must have a email")
    user = self.model(
      email=self.normalize_email(email),
      first_name = first_name,
      last_name = last_name,
      university = university,
      major = major,
      school_year = school_year,
    )
    user.set_password(password)
    user.save(using=self._db)
    return user

  def create_superuser(self,email,password,first_name,last_name,university,major,school_year):
    user = self.create_user(
      email=self.normalize_email(email),
      password=password,
      first_name = first_name,
      last_name = last_name,
      university = university,
      major = major,
      school_year = school_year,
    )
    user.is_admin = True
    user.is_superuser = True
    user.is_staff = True
    user.save(using=self._db)
    return user

class Account(AbstractBaseUser):
  profile_pic = models.ImageField(upload_to='media',default ='/media/default_profile.png')
  email = models.EmailField(verbose_name="email", max_length=60,unique=True)
  first_name = models.CharField(verbose_name="first_name",max_length=20,blank=True)
  last_name = models.CharField(verbose_name="last_name",max_length=20,blank=True)
  bio = models.TextField(default='No Bio At The Moment')
  university = models.CharField(verbose_name="university",max_length = 1000,default ="")
  major = models.CharField(verbose_name="major",max_length=1000,default="")
  school_year = models.CharField(choices = (("1", "Freshman"),("2", "Sophomore"),("3", "Junior"),("4", "Senior"), ("5", "Other")),default="",max_length=1)
  chat_keys = ArrayField(models.BigIntegerField(), default=list, blank=True)
  friends = ArrayField(models.IntegerField(), default=list, blank=True)
  
  date_joined = models.DateTimeField(verbose_name="date joined",auto_now_add=True)
  last_login = models.DateTimeField(verbose_name="last login", auto_now_add=True)
  is_admin = models.BooleanField(default=False)
  is_active = models.BooleanField(default=True)
  is_staff = models.BooleanField(default=False)
  is_superuser = models.BooleanField(default=False)
  
  show_to_public = ArrayField(models.BooleanField(), default=[True, True, True, True, True, True, True, True])
  #[profile_pic, email, first_name, last_name, university, major, school_year, date_joined]
  USERNAME_FIELD = 'email'
  REQUIRED_FIELDS = ['first_name','last_name','university','major','school_year']

  objects = MyAccountManager()

  def __str__(self):
    return self.email
  
  def has_perm(self,perm,obj=None):
    return self.is_admin
  
  def has_module_perms(self, app_label):
    return True

posts_app/forms.py
from django import forms
from .models import PostModel


class PostForm(forms.ModelForm):
  class Meta:
    model = PostModel
    fields = ('title_of_post','description_of_post','skills_needed','num_of_positions','genres', 'application_deadline')

posts_app/views.py
from django.shortcuts import render,reverse
from django.template import RequestContext
from .forms import PostForm
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from.models import PostModel, BookmarkedModel, AppliedPostsModel, AnswerModel
from django.views.generic import ListView
from django.core.exceptions import ObjectDoesNotExist,MultipleObjectsReturned
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect, HttpResponse
from django.utils import timezone
import datetime
from authorize_main.models import Account
from Notifications.models import NotificationModel
from Notifications.views import Notifications
from newsapi import NewsApiClient
from chat.views import chat_key_seeder, create_private_chat, notify_chat, url_scrambler, list_all_people
from django.db.models.functions import Trunc
from friends.views import get_mutual_friends
import json
import urllib

def getbookmarkinfo_allposts(request, post_id, page_number): 
  return make_bookmark(request, post_id, page_number)
  

def redir_2_all_post(request,page_number=1):
  ret = apply_view(request)
  return redirect(f'/posts/all_posts/?page1={page_number}')


def redir_2_bookmarked(request, page_number=1):
  ret = apply_view(request)
  return redirect(f'/posts/bookmarked_posts/?page3={page_number}')


def apply_page(request, page_number): #Load Application page
  post_id = request.POST['postID']
  post = PostModel.objects.get(id=post_id)
  question_num_lst= []

  if post.application_completed == True:
    return HttpResponse('This application has expired') 
  
  application_questions = post.application_questions
  for question in range(1, len(application_questions) + 1):
    question_num_lst.append(str(question))
  
  question_zip = zip(application_questions, question_num_lst)
  
  return render(request, "posts_app/application_questions.html", {'application_questions': question_zip, "post_id": post.id, "page_number":page_number, 'post_name': post.title_of_post}) 
  


def submit_application(request, post_id, page_number): #saves the question and answers to the AnswerModel
  user = Account.objects.get(id=request.user.id)
  post = PostModel.objects.get(id=post_id)
  
  if request.method == 'POST':

    questions = []
    answers = []
    
    if PostModel.objects.get(id=post_id).application_completed == True:
      messages.success(request, 'Application has expired')
      return redirect(f'/posts/all_posts/?page1={page_number}')

    for question_num in range(1, len(post.application_questions) + 1):
      answer = request.POST[str(question_num)]
      answers.append(answer)
      
    if len(AnswerModel.objects.filter(applicant=Account.objects.get(id=request.user.id), post=PostModel.objects.get(id=post_id))) == 0:
      apply_view(request, post_id)
      application = AnswerModel.objects.create(answers=answers, applicant=Account.objects.get(id=request.user.id), post=PostModel.objects.get(id=post_id))
      messages.success(request,"Application successfully submitted")
      return redirect(f'/posts/all_posts/?page1={page_number}')
    else:
      messages.success(request,"Application already submitted")
      return redirect(f'/posts/all_posts/?page1={page_number}') 
    
  messages.success(request,"Application failed")
  return redirect(f'/posts/all_posts/?page1={page_number}')


def apply_view(request, post_id): #Add user to PostAppliedModel
  if request.POST:
    
    post_to_apply = post_id

    user = request.user
  
    applied = AppliedPostsModel.objects.create(account=user,applied_post = PostModel.objects.get(id = post_to_apply))
    applied.id = post_to_apply
    current_post = PostModel.objects.get(id = post_to_apply)
    current_post.applicants.append(request.user.id)
    current_post.save()
  
  else:
    raise Exception('request is not POST')
   
   
def PostApplyList(request): #for poster to see which users applied
  apply_list = AppliedPostsModel.objects.all()
  users_applications = []
  for application in apply_list:
    if application.account.id == request.user.id:
      users_applications.append(apply_list)
  
  return render(request,'posts_app/Applied.html',{"users_applications":users_applications, 'all_notifications': Notifications(request), 'friends':list_all_people()})


def PostList(request, searched=False, results=None, title='', sorted_option=''): #Show all posts in hometemplate
  
  if searched == False:
    postlist = AllAppliedBookmarkedView(request)[0]
  elif searched == True:
    
    paginator_allposts = Paginator(results, 3)
    allposts_number = request.GET.get('page1',1)
    postlist = paginator_allposts.get_page(allposts_number)
    
  newsapi = NewsApiClient(api_key='2d6d2823f99f42aaa163e76c3dbb20fa')
  top_headlines = newsapi.get_top_headlines(language='en',sources='techcrunch')
  all_articles = top_headlines['articles']

  for article in all_articles:
    clock = article['publishedAt']
    date = clock[0:10]
    year = date[0:4]
    month = date[5:7]
    day = date[8:10]

    rearranged = month+'-'+day+'-'+year
    
    time = clock[11:int(len(clock)-4)]
    hours = time[0:2]
    minutes = time[3:5]
    am_or_pm=''
    if(int(hours) >= 12):
      am_or_pm = 'PM'
      hours = str(int(hours)-12)
    else:
      am_or_pm ='AM'
    
    article['publishedAt'] = rearranged+" "+ hours+":"+minutes+" "+am_or_pm
    
  return render(request,'posts_app/home_template.html',{"pag_allposts":postlist, 'all_notifications': Notifications(request),"all_articles":all_articles, 'friends':list_all_people(), 'title': title, 'sorted_option':sorted_option})


def ApplyList(request, searched=False, results=None, title='', sorted_option=''): #for user to see which posts they applied to
  if searched == False:
    appliedposts_obj = AllAppliedBookmarkedView(request)[1]
    applied_posts_urls = AllAppliedBookmarkedView(request)[4]
  elif searched == True:
    
    paginator_allposts = Paginator(results, 3)
    allposts_number = request.GET.get('page2',1) 
    appliedposts_obj = paginator_allposts.get_page(allposts_number)
    urls = []
    for application in results:
      poster_id = application.applied_post.post_made_by.id
      post_id = application.applied_post.id
      if application.accepted:
        url =  url_scrambler(poster_id) + url_scrambler(post_id) + url_scrambler(request.user.id)
        
        urls.append(url)
      else:
        urls.append(0)
    applied_posts_urls = zip(appliedposts_obj, urls)
  return render(request, 'posts_app/Applied.html', {'pag_appliedposts': appliedposts_obj, 'applied_posts_urls': applied_posts_urls, 'all_notifications': Notifications(request), 'friends':list_all_people(), 'title': title, 'sorted_option':sorted_option})


def BookmarkList(request, searched=False, results=None, title='', sorted_option=''): #Shows bookmarks in bookmark page
  if searched == False:
    
    bookmarks_obj = AllAppliedBookmarkedView(request)[2] 
  elif searched == True:
    
    paginator_bookmarks = Paginator(results, 3)
    bookmarks_number = request.GET.get('page3')
    bookmarks_obj = paginator_bookmarks.get_page(bookmarks_number)

  return render(request,'posts_app/Bookmarked.html',{"pag_bookmarks":bookmarks_obj, 'all_notifications': Notifications(request), 'friends':list_all_people(),'title': title, 'sorted_option':sorted_option})  

    
def MyPostList(request, post_id=None,page_number=1, searched=False, results=None, title='', sorted_option=''): #Shows user's posts in user post page
  
  if searched == False:
    mypost_obj = AllAppliedBookmarkedView(request,page_number)[3]    
      
  else:
    paginator_mypost = Paginator(results, 3)
    mypost_number = request.GET.get('page4',page_number)
    mypost_obj = paginator_mypost.get_page(mypost_number)
    
    
  current_post = ''
  users = []
  accepted = []
  chat_url = []
  user_apps = [] 
  
  if post_id:
    post = PostModel.objects.get(id=post_id)
    applicants = post.applicants
    current_post = PostModel.objects.get(id=post_id).title_of_post
    
    for x in post.accepted_applicants:
      accepted.append(Account.objects.get(id=x)) 
    
    for x in post.applicants:
      users.append(Account.objects.get(id=x))

    user_url_combined = []
    
    for x in range(len(accepted)):
      questions = post.application_questions
      application = AnswerModel.objects.get(applicant=accepted[x], post=post) 
      answers = application.answers
      
      url = url_scrambler(request.user.id) + url_scrambler(post_id) + url_scrambler(accepted[x].id)
      create_private_chat(request, url, accepted[x].id, post.id)
      
      combined = [accepted[x], url, zip(questions, answers)]
      user_url_combined.append(combined)
      
    user_apps = []

    for user in range(len(users)):
      user = users[user]
      
      application = AnswerModel.objects.get(applicant=user, post=post)
      
      answers = application.answers
      questions = post.application_questions
      
      combined = [user, zip(questions, answers)]
      user_apps.append(combined)
    
  else:
    user_url_combined = []
    applicants = []
   
  return render(request, 'posts_app/My_Post.html', {"pag_mypost":mypost_obj, 'users': users,"current_post":current_post,
  "num":len(users),"post_id":post_id,"accepted":accepted,"num_accepted":len(accepted), 'all_notifications': Notifications(request),
  'user_url_combined': user_url_combined, 'friends':list_all_people(), 'title': title, 'sorted_option': sorted_option, "user_apps": user_apps})
  
  
def AllAppliedBookmarkedView(request,page_number=None): #Retrieves content for List views: all, applied, bookmarked, myposts
  all_posts = PostModel.objects.all().order_by('id')
  all_posts_filtered = []
  user_posts = []
  user_bookmarks = []

  all_bookmarks = BookmarkedModel.objects.all().order_by('id') 
  applied_posts = AppliedPostsModel.objects.filter(account__id=request.user.id).order_by('id') 
  

posts_app/templates/posts_app/all_posts.html
{%extends 'authorize_main/base.html'%}

{%block content%}

{% if user.is_authenticated %}
      {% if messages %}
      {% for message in messages %}
          <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
      {% endfor %}
      {% endif %}

        <form action= "{%url 'search_results'%}"method = "get">
            {% csrf_token %}
            <input type="search" name="q" id="id_q" minlength="1" placeholder="Enter a title or description">
            <button type ="submit">Search</button>
        </form>
        {% if all_search_results.searched == True %}
            {% if all_search_results.result and all_search_results.found == True %}
                {% for post in all_search_results.result %}
                <h1>{{post.title}}</h1>
                <p>{{post.description}}</p>
                <p>id: {{post.id}}</p>
                <button><a href="{%url 'add_favorite_post' post.id%}">Favorite</a></button>
                {% endfor %}
            {% elif all_search_results.found == False %} 
                <p>Your Search Cannot Be Found</p>
                {% for post in all_search_results.result %}
                <h1>{{post.title}}</h1>
                <p>{{post.description}}</p>
                <p>id: {{post.id}}</p>
                <button><a href="{%url 'add_favorite_post' post.id%}">Favorite</a></button>
                {%edfor%}
            {% endif %}
        {% endif %}
        
        {%for post in post_list%}
            {%if post.account.email != user.email%}
                <h1>{{post.title}}</h1>
                <p>{{post.description}}</p>
                <p>id: {{post.id}}</p>
                <button><a href="{%url 'add_favorite_post' post.id%}">Favorite</a></button>
            {%endif%}
        {%endfor%}
    {% endif %}
{%endblock%}

posts_app/templates/posts_app/application_questions.html
{% extends 'authorize_main/base.html' %}
{% block content %}
{% load static %}
<br><br><br><br><br>
<div class="postApplication">
<h1>Application for {{post_name}} </h1>
<form name='application_questions' method="post" action="{%url 'submitapp' post_id page_number %}">
    {%csrf_token%}
    {% for questions, number in application_questions %}
        <label class="question" for="question">{{questions}}</label>
        <textarea class="text-box" name={{number}} id={{number}} maxlength="200" ></textarea>
    {% endfor %}
    <br>
    <button id="button" onclick="submit();" class="submit" type="submit">Submit</button>
    
</form>
</div>
{% endblock %}

posts_app/templates/posts_app/favorite.html
{%extends 'authorize_main/base.html'%}

{%block content%}

{% if user.is_authenticated %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}
    {%for post in favorite_posts%}
    <h1>{{post.favorite_post.title}}</h1>
    <p>{{post.favorite_post.description}}</p>
    <p>id: {{post.id}}</p>
    <button><a href="{%url 'delete_favorite' post.id%}">Delete</a></button>
    {%endfor%}
{% endif%}

{%endblock%}

posts_app/templates/posts_app/post_page copy.html
{%extends 'authorize_main/base.html'%}

{%block content%}
  {%if message%}
  <p>{{message}}</p>
  {%endif%}
  <form method = "post">
    {%csrf_token%}
    {%for field in form%}
      <h1>{{field.label_tag}}</h1>
      {{field}}
    {%endfor%}
    <button type="submit">Submit</button>
  </form>
{%endblock%}

posts_app/templates/posts_app/post_page.html
{%extends 'authorize_main/base.html'%}

{%block content%}
  {%if message%}
  <p>{{message}}</p>
  {%endif%}
  <form method = "post">
    {%csrf_token%}
    {%for field in form%}
      <h1>{{field.label_tag}}</h1>
      {{field}}
    {%endfor%}
    <button type="submit">Submit</button>
  </form>
{%endblock%}

posts_app/templates/posts_app/pub_profile.html
{% extends 'authorize_main/base.html' %} {%load static%} {%block content%}

<link rel="stylesheet" href="{%static 'authorize_main/profile.css'%}">
<link rel="stylesheet" href="{%static 'posts_app/pub_profile.css'%}" />
<script src ="{%static 'posts_app/js/emoji-button-3.1.1.min.js'%}" ></script>
<!-- <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous">
</script>
<script src= "{%static 'posts_app/js/emojionearea.js'%}"></script>
<link rel="stylesheet" href="{%static 'posts_app/emojionearea.css'%}"> -->
<div class="profilefriendsList">
  <h1 style="text-align:center;margin-top:20px;color:white;font-weight:bold;">Mutual Colleagues</h1>
  <br>
  <div class="profilefriendsBox">
    {% for friend in common_friends %}
    <br>
    <div class="profilefriendsButton">
      <a href ="{% url 'applicant_profile' friend.id %}">
        <img style='min-width:50px;max-width:50px;min-height:50px;max-height:50px;' src="{{friend.profile_pic.url}}"/>
        <h1 style='margin-left:50px;'>{{ friend.first_name }} {{friend.last_name}}</h1>
      </a>
    </div>
  {% endfor %}
</div>
</div>
 
<div class="Profilebox">
 
  {%if is_friend == False %}
  <a class="AddFriend" href="{% url 'send_friend_request' applicant.id %}">Send Friend Request</a>
  {%else%}
  <a title="Start Chatting!"style="position:absolute;margin-top:5px;margin-left:10px;font-size:50px;text-decoration:none;"href="">
    <i class='far fa-comments'></i>
  </a>
  <a style="color: white;" class="AddFriend">Already Friended</a>
  {%endif%}
  
  <img
    class="profpic"
    src="{{profile_pic}}"
    alt="Profile Picture Not Uploaded"
  />
  <h1 class="pubuname">{{applicant.first_name}} {{applicant.last_name}}</h1>
  <h3 class="pubemail"><strong>Email: </strong><span>{{email}}</span></h3>
  <h3 class="pubuni">
    <strong>University: </strong><span> {{applicant.university}}</span>
  </h3>
  <h3 class="pubmaj">
    <strong>Major: </strong><span> {{applicant.major}}</span>
  </h3>
  <h3 class="pubschy">
    <strong>School Year: </strong
    ><span> {{applicant.get_school_year_display}}</span>
  </h3>
  <h3 class="pubBio">
    <strong class="pubBioS">Bio: </strong>
    <p class="biospan">&emsp;&emsp;{{applicant.bio}}</p>
  </h3>
</div>






{%endblock%}

posts_app/templates/posts_app/see_my_posts.html
{%extends 'authorize_main/base.html'%}

{%block content%}

{% if user.is_authenticated %}
    {%for post in post_list%}
    <h1>{{post.title}}</h1>
    <p>{{post.description}}</p>
    <button ><a href="{%url 'delete' post.id %}">Remove Post</a></button>
    {%endfor%}
{% endif%}

{%endblock%}

                